### ISSUE TITLE
Would it be possible to swap the Alt and Command keys with this?

### ISSUE THREAD

**Issue by alexliew** [whereswaldon/kfreestyle2d#14]
Thanks for creating this! I learned a lot reading your blog about this. I have the Mac version of this keyboard which has the bottom left keys as Ctrl-Alt-Command instead of the Ctrl-Win-Alt on the PC version of the keyboard. Could that order be changed to the Windows order by changing the mapping in k.c?

Thanks!

**Comment by whereswaldon** [comment]
> Thanks for creating this!

@alexliew You're welcome. :D 

> I have the Mac version of this keyboard which has the bottom left keys as Ctrl-Alt-Command instead of the Ctrl-Win-Alt on the PC version of the keyboard. Could that order be changed to the Windows order by changing the mapping in k.c?

Good news and bad news. The bad news is that k.c only remaps a set of weird HID Usage IDs that Linux doesn't natively recognize into some that it does, but the keys you're interested in are all normally recognized, so they aren't part of the ones that k.c handles.

The good news is that there's a ton of great software out there that _can_ do what you want without kfreestyle2d (or alongside it). I recommend looking at the [Keyboard remapper section here](https://arewewaylandyet.com/). Those softwares are generally able to function within X11, Wayland, and on a raw TTY, so I'd prefer them to using `xmodmap` (which will only work under X11 desktops).

Anyway, I think this should be quite easy to achieve, and you get a chance to explore a number of exciting looking projects (I haven't personally used any of them). Good luck, and have fun! I'm going to close this issue, but feel free to share your results here if you find a solution you like. Others may follow with similar questions.
